#pragma once
// TODO Fill more as needed

typedef enum {
    TILE_CHEST = 0x00,
    TILE_GOLD_SACK = 0x01,
    TILE_POTION = 0x02,
    TILE_SCROLL = 0x03,
    TILE_SWORD = 0x04,
    TILE_SHIELD = 0x05,
    TILE_KEY = 0x06,
    TILE_GEM = 0x07,
    TILE_HELMET = 0x08,
    TILE_RING = 0x09,
    TILE_ARMOR = 0x0a,
    TILE_AMULET = 0x0b,
    TILE_TORCH = 0x0c,
    TILE_BOX = 0x0e,
    TILE_FOOD = 0x0f,

    TILE_SHARD = 0xb4,
    TILE_CROWN = 0xb5,
    TILE_SCEPTRE = 0xb6,
    TILE_AMULET = 0xb7,

    TILE_FIELD = 0xe8,
    TILE_POISON_FIELD = 0xe8,
    TILE_SLEEP_FIELD = 0xe9,
    TILE_FIRE_FIELD = 0xea,
    TILE_ENERGY_FIELD = 0xeb,
} HighTile;

// Zeroes two lowest bytes, snaps a 4-tile animated monster frame to the base
// frame index.
#define ANIM_BASE_MASK 0xfc

#define NUM_MONSTERS 32

typedef enum {
    LEATHER_HELM = 0x00,
    CHAIN_COIF = 0x01 ,
    IRON_HELM = 0x02,
    SPIKED_HELM = 0x03,
    SMALL_SHIELD = 0x04,
    LARGE_SHIELD = 0x05,
    SPIKED_SHIELD = 0x06,
    MAGIC_SHIELD = 0x07,
    JEWEL_SHIELD = 0x08,
    CLOTH_ARMOUR = 0x09,
    LEATHER_ARMOUR = 0x0a,
    RINGMAIL = 0x0b,
    SCALE_MAIL = 0x0c,
    CHAIN_MAIL = 0x0d,
    PLATE_MAIL = 0x0e,
    MYSTIC_ARMOUR = 0x0f,
    DAGGER = 0x10,
    SLING = 0x11,
    CLUB = 0x12,
    FLAMING_OIL = 0x13,
    MAIN_GAUCHE = 0x14,
    SPEAR = 0x15,
    THROWING_AXE = 0x16,
    SHORT_SWORD = 0x17,
    MACE = 0x18,
    MORNING_STAR = 0x19,
    BOW = 0x1a,
    ARROWS = 0x1b,
    CROSSBOW = 0x1c,
    QUARRELS = 0x1d,
    LONG_SWORD = 0x1e,
    TWO_H_HAMMER = 0x1f,
    TWO_H_AXE = 0x20,
    TWO_H_SWORD = 0x21,
    HALBERD = 0x22,
    SWORD_OF_CHAOS = 0x23,
    MAGIC_BOW = 0x24,
    SILVER_SWORD = 0x25,
    MAGIC_AXE = 0x26,
    GLASS_SWORD = 0x27,
    JEWELED_SWORD = 0x28,
    MYSTIC_SWORD = 0x29,
    RING_INVISIBILITY = 0x2a,
    RING_PROTECTION = 0x2b,
    RING_REGENERATION = 0x2c,
    AMULET_TURNING = 0x2d,
    SPIKED_COLLAR = 0x2e,
    ANKH = 0x2f,
    VAS_LOR_SCR = 0x30,
    REL_HUR_SCR = 0x31,
    IN_SANCT_SCR = 0x32,
    IN_AN_SCR = 0x33,
    IN_QUAS_WIS_SCR = 0x34,
    KAL_XEN_CORP_SCR = 0x35,
    AN_TYM_SCR = 0x36,
} Equipment;
